name: Update Visitor Count

on:
  schedule:
    - cron: '0 * * * *'  # Update every hour

jobs:
  update_visitor_count:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Update README
        run: |
          badge_url="![Static Badge](https://img.shields.io/badge/Visitor-Count?style=social&label=VisitorCount&labelColor=abcdef&color=fedcba)"
          sed -i "s#YOUR_BADGE_URL#$badge_url#g" README.md
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -am "Update visitor count [skip ci]" || exit 0
          git push
